name: eatq
description: "음식 주문 앱"

# 다음 줄을 추가해야 합니다
environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.4.0
  go_router: ^12.0.0
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0
  uuid: ^4.1.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/